name: Security and Compliance Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@v1

- name: Generate SBOM
  run: |
    curl -L -o sbom-tool.tar.gz https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64.tar.gz
    mkdir sbom-tool
    tar -xzf sbom-tool.tar.gz -C sbom-tool
    ./sbom-tool/sbom-tool generate -b . -bc . -pn "CustomerWorkload" -pv "1.0.0" -ps "PartnerOrg" -nsb https://sbom.partner.org -V Verbose

    - name: Export Azure Policy Compliance (manual step)
      run: echo "Export Azure Policy compliance results from Azure Portal or via CLI."
